### ISSUE TITLE
SW1: Replicate RPDE logic in Ruby

### ISSUE THREAD

**Issue by thill-odi** [openactive/models-ruby#3]
0.5d

**Comment by nickevansuk** [comment]
One response to Rails version question: Rails 5 latest (not on 6 yet). And ruby 2.4 latest for now.

**Comment by henryaddison** [comment]
Is the idea for this task to port the .net implementation? https://github.com/openactive/OpenActive.NET/blob/master/OpenActive.NET/rpde/RDPEModels.cs

**Comment by nickevansuk** [comment]
Basically yep, with crystal clear documentation for how to use it (which the .NET version is sorely lacking)

**Comment by nickevansuk** [comment]
This has been completed
