### ISSUE TITLE
Missing Schedule scheduleTimezone property definition

### ISSUE THREAD

**Issue by el-quick** [openactive/models-ruby#33]
As described here: https://developer.openactive.io/data-model/types/schedule `scheduleTimezone` is a required property for Schedule, but its definition is not implemented:

https://github.com/openactive/models-ruby/blob/a14130b3c545103480f89f4623a6331b41089cb2/lib/openactive/models/schedule.rb

Resulting on this error message
`#<NoMethodError: undefined method schedule_timezone=' for #<OpenActive::Models::Schedule:0x00007fb576c4d2a8>`

**Comment by nickevansuk** [comment]
This should now be resolved in 0.2.0
